/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : get-windows-version
 #	author : miyako
 #	2015/09/04
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

#include <vector>

#define kGetFileVersionInfo 1
#define kGetVersionInfoEx 0

void PluginMain(PA_long32 selector, PA_PluginParameters params)
{
	try
	{
		PA_long32 pProcNum = selector;
		sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
		PackagePtr pParams = (PackagePtr)params->fParameters;

		CommandDispatcher(pProcNum, pResult, pParams); 
	}
	catch(...)
	{

	}
}

void CommandDispatcher (PA_long32 pProcNum, sLONG_PTR *pResult, PackagePtr pParams)
{
	switch(pProcNum)
	{
// --- Windows

		case 1 :
			Windows_Is_WOW64(pResult, pParams);
			break;

		case 2 :
			Windows_Get_version(pResult, pParams);
			break;

	}
}

// ------------------------------------ Windows -----------------------------------

BOOL IsWow64()
{
    BOOL bIsWow64 = FALSE;
#if VERSIONWIN
    typedef BOOL(WINAPI *LPFN_ISWOW64PROCESS) (HANDLE, PBOOL);
    LPFN_ISWOW64PROCESS fnIsWow64Process;
    fnIsWow64Process = (LPFN_ISWOW64PROCESS)GetProcAddress(
        GetModuleHandle(TEXT("kernel32")), "IsWow64Process");

    if (NULL != fnIsWow64Process)
    {
        if (!fnIsWow64Process(GetCurrentProcess(), &bIsWow64))
        {
            // the call failed: bIsWow64 is not meaningful, report "not WOW64"
            bIsWow64 = FALSE;
        }
    }
#endif
    return bIsWow64;
}

void Windows_Is_WOW64(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_LONGINT returnValue;

	returnValue.setIntValue(IsWow64());
	returnValue.setReturn(pResult);
}

BOOL getVersion(C_LONGINT &major, C_LONGINT &minor){
#if VERSIONWIN
    // https://msdn.microsoft.com/en-us/library/ms724833(v=vs.85).aspx
	OSVERSIONINFOEX versionInfo;
	ZeroMemory(&versionInfo, sizeof(OSVERSIONINFOEX));
	versionInfo.dwOSVersionInfoSize = sizeof(OSVERSIONINFOEX);
    if(GetVersionEx((OSVERSIONINFO*)&versionInfo)){
        major.setIntValue(versionInfo.dwMajorVersion);
        minor.setIntValue(versionInfo.dwMinorVersion);
		return TRUE;
    }
#endif
    return FALSE;
}

BOOL getKernel32Version(C_LONGINT &major, C_LONGINT &minor){
#if VERSIONWIN
    // uSize is a count of characters, not bytes
    WCHAR pszPath[MAX_PATH];
    const UINT cchPath = sizeof(pszPath) / sizeof(pszPath[0]);
    UINT len = GetSystemDirectoryW(pszPath, cchPath);
    if ((len == 0) || (len >= cchPath))
        return FALSE; // failed, or buffer too small (contents undefined)

    if (!PathAppendW(pszPath, L"kernel32.dll"))
        return FALSE;

    DWORD dwSize = GetFileVersionInfoSizeW(pszPath, NULL);
    if (dwSize == 0)
        return FALSE;

    // std::vector releases the buffer on every return path (was leaked before)
    std::vector<BYTE> versionInfo(dwSize);
    if (!GetFileVersionInfoW(pszPath, 0, dwSize, &versionInfo[0]))
        return FALSE;

    VS_FIXEDFILEINFO *pFileInfo = NULL;
    UINT puLenFileInfo = 0;
    if (!VerQueryValueW(&versionInfo[0], L"\\", (LPVOID*)&pFileInfo, &puLenFileInfo))
        return FALSE;
    if ((pFileInfo == NULL) || (puLenFileInfo < sizeof(VS_FIXEDFILEINFO)))
        return FALSE;

    // dwProductVersionMS packs major (high word) and minor (low word);
    // the layout does not depend on process bitness, so no WOW64 check is needed
    major.setIntValue(HIWORD(pFileInfo->dwProductVersionMS));
    minor.setIntValue(LOWORD(pFileInfo->dwProductVersionMS));
    return TRUE;
#else
    return FALSE;
#endif
}

// http://stackoverflow.com/questions/9817160/getversionex-under-windows-8

void setVersionString(C_TEXT &version, C_LONGINT &major, C_LONGINT &minor){

#if VERSIONWIN
	uint8_t buf[99];
	snprintf((char *)buf, sizeof(buf), "%i.%i", (int)major.getIntValue(), (int)minor.getIntValue());
	CUTF8String _version(buf);
    version.setUTF8String(&_version);
#endif
}

void Windows_Get_version(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_LONGINT Param1;
	C_TEXT returnValue;
    C_LONGINT major, minor;
    
	Param1.fromParamAtIndex(pParams, 1);

    // catch locally so the result is always set, even if something throws
    // (e.g. std::bad_alloc); the catch-all in PluginMain has no way to set it
    try {
        switch (Param1.getIntValue()) {
          case kGetFileVersionInfo:
            if(getKernel32Version(major, minor))
                setVersionString(returnValue, major, minor);
            break;
          default:
            if(getVersion(major, minor))
                setVersionString(returnValue, major, minor);
            break;
        }
    } catch(...) {
        // leave returnValue as an empty string
    }
    
	returnValue.setReturn(pResult);
}
