/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : get-windows-version
 #	author : miyako
 #	2015/09/04
 #
 # --------------------------------------------------------------------------------*/

#if VERSIONWIN
#define _WIN32_DCOM
#include "Shlwapi.h"
#pragma comment(lib, "Shlwapi.lib")
#pragma comment(lib, "Version.lib")
#endif

// --- Windows
void Windows_Is_WOW64(sLONG_PTR *pResult, PackagePtr pParams);
void Windows_Get_version(sLONG_PTR *pResult, PackagePtr pParams);
